apiVersion: v1
kind: PersistentVolume
metadata:
  name: fp-local-pv
spec:
  capacity:
    storage: 5M
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fp-local-sc
  local:
    path: /opt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
