# Default values for fp-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
secretname: fp-private-registry

image:
  repository: fpregistry.local:5000/echo
  name: fp-echo-svc
  pullPolicy: IfNotPresent
  tag: 1
  port: 50007

service:
  type: NodePort
  port: 50017
  nodeport: 30007
