apiVersion: v1
kind: Service
metadata:
  name: fp-service
spec:
  type: NodePort
  selector:
    app: fp-test-echosvc
  ports:
    - protocol: TCP
      port: 50017
      targetPort: 50007
      nodePort: 30007