apiVersion: v1
kind: PersistentVolume
metadata:
  name: fp-pv-nfs
spec:
  capacity:
    storage: 1M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /opt/nfsshare
    server: 192.168.0.36