apiVersion: v1
kind: Service
metadata:
  name: fp-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fp-test-echosvc
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      nodePort: {{ .Values.service.nodeport }}